//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bot_Manager {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Test {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Test() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bot_Manager.Test", typeof(Test).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO ANUNCIOS VALUES.
        /// </summary>
        internal static string SQL_ADD_AN {
            get {
                return ResourceManager.GetString("SQL_ADD_AN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO CLASSIC_NITRO VALUES.
        /// </summary>
        internal static string SQL_ADD_CNITRO {
            get {
                return ResourceManager.GetString("SQL_ADD_CNITRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO Guild VALUES.
        /// </summary>
        internal static string SQL_ADD_GUILD {
            get {
                return ResourceManager.GetString("SQL_ADD_GUILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO INACTIVE_NITRO VALUES.
        /// </summary>
        internal static string SQL_ADD_INITRO {
            get {
                return ResourceManager.GetString("SQL_ADD_INITRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO Itens_Variados VALUES.
        /// </summary>
        internal static string SQL_ADD_Item {
            get {
                return ResourceManager.GetString("SQL_ADD_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string SQL_ADD_Scash {
            get {
                return ResourceManager.GetString("SQL_ADD_Scash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO User VALUES.
        /// </summary>
        internal static string SQL_ADD_USER {
            get {
                return ResourceManager.GetString("SQL_ADD_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO VENDASOK VALUES.
        /// </summary>
        internal static string SQL_ADD_VENDA {
            get {
                return ResourceManager.GetString("SQL_ADD_VENDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UPDATE Guild SET Log_Channel =.
        /// </summary>
        internal static string SQL_addLog1 {
            get {
                return ResourceManager.GetString("SQL_addLog1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WHERE Id = .
        /// </summary>
        internal static string SQL_addLog2 {
            get {
                return ResourceManager.GetString("SQL_addLog2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT Jcash, Scash FROM User WHERE Id = .
        /// </summary>
        internal static string SQL_cash_Read {
            get {
                return ResourceManager.GetString("SQL_cash_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT * FROM ANUNCIOS.
        /// </summary>
        internal static string SQL_GET_AN {
            get {
                return ResourceManager.GetString("SQL_GET_AN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT Link FROM Classic_Nitro.
        /// </summary>
        internal static string SQL_GET_CNitro {
            get {
                return ResourceManager.GetString("SQL_GET_CNitro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT Link FROM Inactive_Nitro.
        /// </summary>
        internal static string SQL_GET_Initro {
            get {
                return ResourceManager.GetString("SQL_GET_Initro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT Id, Log_Channel FROM Guild.
        /// </summary>
        internal static string SQL_Id_Log {
            get {
                return ResourceManager.GetString("SQL_Id_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT Id FROM User.
        /// </summary>
        internal static string SQL_Id_User {
            get {
                return ResourceManager.GetString("SQL_Id_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DELETE FROM ANUNCIOS WHERE USER = .
        /// </summary>
        internal static string SQL_REMOVE_AN {
            get {
                return ResourceManager.GetString("SQL_REMOVE_AN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UPDATE User SET .
        /// </summary>
        internal static string SQL_UPDATE_Cash {
            get {
                return ResourceManager.GetString("SQL_UPDATE_Cash", resourceCulture);
            }
        }
    }
}
