//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bot_Manager {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Test {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Test() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bot_Manager.Test", typeof(Test).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO ANUNCIOS VALUES.
        /// </summary>
        internal static string SQL_ADD_AN {
            get {
                return ResourceManager.GetString("SQL_ADD_AN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO CLASSIC_NITRO VALUES.
        /// </summary>
        internal static string SQL_ADD_CNITRO {
            get {
                return ResourceManager.GetString("SQL_ADD_CNITRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO Guild VALUES.
        /// </summary>
        internal static string SQL_ADD_GUILD {
            get {
                return ResourceManager.GetString("SQL_ADD_GUILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO INACTIVE_NITRO VALUES.
        /// </summary>
        internal static string SQL_ADD_INITRO {
            get {
                return ResourceManager.GetString("SQL_ADD_INITRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO Itens_Variados VALUES.
        /// </summary>
        internal static string SQL_ADD_Item {
            get {
                return ResourceManager.GetString("SQL_ADD_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string SQL_ADD_Scash {
            get {
                return ResourceManager.GetString("SQL_ADD_Scash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO User VALUES.
        /// </summary>
        internal static string SQL_ADD_USER {
            get {
                return ResourceManager.GetString("SQL_ADD_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO VENDASOK VALUES.
        /// </summary>
        internal static string SQL_ADD_VENDA {
            get {
                return ResourceManager.GetString("SQL_ADD_VENDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UPDATE Guild SET Log_Channel =.
        /// </summary>
        internal static string SQL_addLog1 {
            get {
                return ResourceManager.GetString("SQL_addLog1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WHERE Id = .
        /// </summary>
        internal static string SQL_addLog2 {
            get {
                return ResourceManager.GetString("SQL_addLog2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT Jcash, Scash FROM User WHERE Id = .
        /// </summary>
        internal static string SQL_cash_Read {
            get {
                return ResourceManager.GetString("SQL_cash_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT * FROM ANUNCIOS.
        /// </summary>
        internal static string SQL_GET_AN {
            get {
                return ResourceManager.GetString("SQL_GET_AN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT Link FROM Classic_Nitro.
        /// </summary>
        internal static string SQL_GET_CNitro {
            get {
                return ResourceManager.GetString("SQL_GET_CNitro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT Link FROM Inactive_Nitro.
        /// </summary>
        internal static string SQL_GET_Initro {
            get {
                return ResourceManager.GetString("SQL_GET_Initro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT * FROM ITENS_VARIADOS.
        /// </summary>
        internal static string SQL_GET_ITENS {
            get {
                return ResourceManager.GetString("SQL_GET_ITENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT Id, Log_Channel FROM Guild.
        /// </summary>
        internal static string SQL_Id_Log {
            get {
                return ResourceManager.GetString("SQL_Id_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT Id FROM User.
        /// </summary>
        internal static string SQL_Id_User {
            get {
                return ResourceManager.GetString("SQL_Id_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DELETE FROM ANUNCIOS WHERE USER = .
        /// </summary>
        internal static string SQL_REMOVE_AN {
            get {
                return ResourceManager.GetString("SQL_REMOVE_AN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a select * from vendasok where vendido_para = {id}
        ///order by(dt_venda) desc.
        /// </summary>
        internal static string SQL_SELECT_VENDASOK {
            get {
                return ResourceManager.GetString("SQL_SELECT_VENDASOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CREATE TABLE Anuncios (
        ///    User       VARCHAR (60) REFERENCES User (Id) 
        ///                            NOT NULL,
        ///    Item       VARCHAR (60) NOT NULL,
        ///    Item_qtde  VARCHAR (30),
        ///    Item_valor VARCHAR (30) NOT NULL,
        ///    Pag_tipo                NOT NULL
        ///);.
        /// </summary>
        internal static string SQL_TB_AN {
            get {
                return ResourceManager.GetString("SQL_TB_AN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CREATE TABLE Classic_Nitro (
        ///    Link VARCHAR (60) NOT NULL
        ///                    UNIQUE
        ///);.
        /// </summary>
        internal static string SQL_TB_CNITRO {
            get {
                return ResourceManager.GetString("SQL_TB_CNITRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CREATE TABLE Guild (
        ///    Id          VARCHAR (50) PRIMARY KEY
        ///                             NOT NULL
        ///                             UNIQUE,
        ///    Owner       VARCHAR (65) NOT NULL,
        ///    Log_Channel VARCHAR (50) 
        ///);.
        /// </summary>
        internal static string SQL_TB_GUILD {
            get {
                return ResourceManager.GetString("SQL_TB_GUILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CREATE TABLE Inactive_Nitro (
        ///    Link VARCHAR (60) NOT NULL
        ///                    UNIQUE
        ///);.
        /// </summary>
        internal static string SQL_TB_INITRO {
            get {
                return ResourceManager.GetString("SQL_TB_INITRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CREATE TABLE Itens_Variados (
        ///    Nome   TEXT (80)    NOT NULL
        ///                        DEFAULT (false),
        ///    Item   VARCHAR (60) UNIQUE
        ///                        NOT NULL,
        ///    Jprice INTEGER      NOT NULL,
        ///    Sprice INTEGER      NOT NULL
        ///);.
        /// </summary>
        internal static string SQL_TB_IVAR {
            get {
                return ResourceManager.GetString("SQL_TB_IVAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CREATE TABLE User (
        ///    Id            VARCHAR (50) PRIMARY KEY
        ///                               UNIQUE
        ///                               NOT NULL,
        ///    Scash         INT          NOT NULL
        ///                               CONSTRAINT [Valor inicial] DEFAULT (1500),
        ///    Date_Register DATE         NOT NULL,
        ///    Jcash         INT
        ///);.
        /// </summary>
        internal static string SQL_TB_USER {
            get {
                return ResourceManager.GetString("SQL_TB_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CREATE TABLE VendasOk (
        ///    Item_Name    VARCHAR (60) NOT NULL,
        ///    Link         VARCHAR (60) UNIQUE,
        ///    Price        INT,
        ///    dt_venda     VARCHAR (15) NOT NULL,
        ///    Vendido_para VARCHAR (60) NOT NULL,
        ///    Tipo_moeda   VARCHAR (15) 
        ///);.
        /// </summary>
        internal static string SQL_TB_VENDASOK {
            get {
                return ResourceManager.GetString("SQL_TB_VENDASOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UPDATE User SET .
        /// </summary>
        internal static string SQL_UPDATE_Cash {
            get {
                return ResourceManager.GetString("SQL_UPDATE_Cash", resourceCulture);
            }
        }
    }
}
